version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports: 
      - '3000:3000'
    depends_on:
      - redis
      - mongo
    env_file:
      - ../.env

  redis:
    image: 'redis:alpine'
    ports: 
      - '6379:6379'
    
  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: